### ISSUE TITLE
AudioMidiSyncHelper issues

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/Kars#1]
I'm using an LV2 build of the plugin from latest git, running inside Carla.

If I swipe the Carla piano widget with the mouse cursor (as in a Glissando), I get silence + this error output for every note:

```assertion failure: "eventFrame < remainingFrames" in file DistrhoPluginKars.cpp, line 188```

These two variables have a value of 0.

Also, ticking Fixed-Size Buffer makes the plugin segfault when playing notes with a midi controller (but not with the piano widget). This might be a Carla bug, though (I'm using latest git Carla from the master branch):
```
Thread 1 "carla" received signal SIGSEGV, Segmentation fault.
0x00007ffff679ccd2 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
INSERT (gdb) bt
#0  0x00007ffff679ccd2 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#1  0x00007ffff67ed9d4 in  () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff5dab3cf in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5dacf89 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff5dacfce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff67ecfc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#6  0x00007fffdb1d9da2 in  () at /usr/lib/libQt5XcbQpa.so.5
#7  0x00007ffff67988cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff67a0bc6 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#9  0x00007ffff21aa5cd in  () at /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so
#10 0x00007ffff7b721c8 in _PyMethodDef_RawFastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#11 0x00007ffff7b72461 in _PyCFunction_FastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#12 0x00007ffff7be2209 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.7m.so.1.0
#13 0x00007ffff7b71a3b in _PyFunction_FastCallKeywords () at /usr/lib/libpython3.7m.so.1.0
#14 0x00007ffff7bdd522 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.7m.so.1.0
#15 0x00007ffff7b2b879 in _PyEval_EvalCodeWithName () at /usr/lib/libpython3.7m.so.1.0
#16 0x00007ffff7b2c7a4 in PyEval_EvalCodeEx () at /usr/lib/libpython3.7m.so.1.0
#17 0x00007ffff7b2c7cc in PyEval_EvalCode () at /usr/lib/libpython3.7m.so.1.0
#18 0x00007ffff7c551e4 in  () at /usr/lib/libpython3.7m.so.1.0
#19 0x00007ffff7c566ee in PyRun_FileExFlags () at /usr/lib/libpython3.7m.so.1.0
#20 0x00007ffff7c59c45 in PyRun_SimpleFileExFlags () at /usr/lib/libpython3.7m.so.1.0
#21 0x00007ffff7c5bf43 in  () at /usr/lib/libpython3.7m.so.1.0
#22 0x00007ffff7c5c14c in _Py_UnixMain () at /usr/lib/libpython3.7m.so.1.0
#23 0x00007ffff7dba223 in __libc_start_main () at /usr/lib/libc.so.6
#24 0x000055555555505e in _start ()
```

**Comment by falkTX** [comment]
Fixed in 8e5dfcd69e1891be1f424b6e2a5874c7aa7f7a44
